name: Build and Sign APK (On Command)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: Generate Signed APK
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/build-apk') &&
      contains('MEMBER,OWNER,COLLABORATOR', github.event.comment.author_association)
    runs-on: ubuntu-latest

    steps:
      # 1) Resolve PR metadata (needed for fork detection and checkout)
      - name: Get PR metadata
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const prNum = context.payload.issue.number;
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNum,
            });
            core.setOutput('head_repo', pr.data.head.repo.full_name);
            core.setOutput('head_ref',  pr.data.head.ref);
            core.setOutput('base_repo', pr.data.base.repo.full_name);
            core.setOutput('base_ref',  pr.data.base.ref);

      # 2) Guard against forked PRs BEFORE any commenting or secrets
      - name: Guard against forked PRs
        id: fork-guard
        run: |
          if [ "${{ steps.pr.outputs.head_repo }}" != "${{ steps.pr.outputs.base_repo }}" ]; then
            echo "This is a forked PR; skipping signed build + comments."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      # 3) Only acknowledge if we're allowed to comment (non-fork)
      - name: Acknowledge command
        if: steps.fork-guard.outputs.skip == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const prNum = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNum,
              body: `👋 Received command \`${context.payload.comment.body.trim()}\`. Starting build…`
            });

      # 4) Stop early on forked PRs (no secrets, no comments)
      - name: Stop job on forked PR
        if: steps.fork-guard.outputs.skip == 'true'
        run: exit 0

      # 5) Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.head_repo }}
          ref: ${{ steps.pr.outputs.head_ref }}
          fetch-depth: 0

      # 6) Tooling
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      # 7) Keystore + build (secrets only on non-fork)
      - name: Decode Keystore from Secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.keystore

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Signed Release APK
        working-directory: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease --no-daemon

      # 8) Artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MobileApp.apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      # 9) Final comment only when allowed
      - name: Comment build result
        if: steps.fork-guard.outputs.skip == 'false' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const prNum = context.payload.issue.number;
            const ok = '${{ job.status }}' === 'success';
            const msg = ok
              ? "✅ Signed APK built successfully. Download it from the **Artifacts** section of this run (MobileApp.apk)."
              : "❌ Build failed. Please check the workflow logs for details.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNum,
              body: msg
            });
